import { Plus_Jakarta_Sans } from 'next/font/google'
import { Navbar } from '../components/navbar/Navbar'
import './globals.css'
import Main from '../components/main/Main'

const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={jakarta.className}>
          <Navbar/>
          {children}
      </body>
    </html>
  )
}